#Generated by VPC

NAME=ScaleformUI
TARGET_PLATFORM=linux64
TARGET_PLATFORM_EXT=_client
VPC_HOST=linux

SRCROOT=..
LINUX_MAKEFILE=1
USE_VALVE_BINDIR=0
# If no configuration is specified, "release" will be used.
CFG ?= release




















################################################################################
#
# CFG=debug
#
################################################################################

ifeq "$(CFG)" "debug"

GCC_ExtraCompilerFlags=
GCC_ExtraCxxCompilerFlags=
GCC_ExtraLinkerFlags=
DisableLinkerDeadCodeElimination=
SymbolVisibility=hidden
TreatWarningsAsErrors=false
OptimizerLevel=-gdwarf-4 -g2 $(OptimizerLevel_CompilerSpecific)
PrecompiledHeaderInclude=
SystemLibraries=-lGL 
DLL_EXT=_client.so
SYM_EXT=.dbg
DEVTOOLS := ../devtools
MAKEFILE_BASE := $(DEVTOOLS)/makefile_base_posix.mak
COMPILE_DEPENDANT_MAKEFILES := scaleformui_linux64.mak $(MAKEFILE_BASE)
FORCEINCLUDES= 
DEFINES += -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DDEBUG -D_DEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=scaleformui -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=scaleformui -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DINCLUDE_SCALEFORM -DENABLE_AMP_SERVER=$ENABLE_AMP_SERVER -DVERSION_SAFE_STEAM_API_INTERFACES -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DSF_BUILD_SHIPPING -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/universe/Downloads/cstrike15_src/scaleformui -DVPCGAME=csgo -DVPCGAMECAPS=CSGO 
INCLUDEDIRS += ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ../scaleformui ../thirdparty/scaleform/sdk42/Include ../thirdparty/scaleform/sdk42/Src ../thirdparty ../common/gl 
CONFTYPE=dll
IMPORTLIBRARY=
OUTPUTFILE=$(OBJ_DIR)/scaleformui_client.so
GAMEOUTPUTFILE=../../game/bin/linux64/scaleformui_client.so

CPPFILES= \
    ../public/tier0/memoverride.cpp \
    stdafx.cpp \
    scaleformuiimpl/movieslot.cpp \
    scaleformuiimpl/scaleformuicursorimpl.cpp \
    scaleformuiimpl/scaleformuihighlevelimpl.cpp \
    scaleformuiimpl/scaleformuiinitimpl.cpp \
    scaleformuiimpl/scaleformuimovieimpl.cpp \
    scaleformuiimpl/scaleformuimovieslotimpl.cpp \
    scaleformuiimpl/scaleformuiparamsimpl.cpp \
    scaleformuiimpl/scaleformuirendererimpl.cpp \
    scaleformuiimpl/scaleformuitranslationimpl.cpp \
    scaleformuiimpl/scaleformuivalueimpl.cpp \
    scaleformuiimpl/scaleformuiintegration.cpp \
    scaleformuiimpl/scaleformuitextobjimpl.cpp \
    scaleformuiimpl/scaleformuiimage.cpp \
    scaleformuiimpl/sfuiavatarimage.cpp \
    scaleformuiimpl/sfuichromehtmlimage.cpp \
    scaleformuiimpl/sfuiinventoryimage.cpp

unexport CPPFILES

LIBFILES = \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/mathlib_client.a \
    ../lib/public/linux64/bitmap_client.a \
    ../lib/public/linux64/tier2_client.a \
    ../lib/public/linux64/tier3_client.a \
    ../lib/public/linux64/vtf_client.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxplatform.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx_as2.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxexpat.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxrender_gl.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libjpeg.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libpng.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libz.a \
    -L../lib/public/linux64 -ltier0_client \
    -L../lib/public/linux64 -lvstdlib_client \
    -L../lib/public/linux64 -lsteam_api \
    -L../lib/public/linux64 -ltogl_client

unexport LIBFILES

LIBFILENAMES = \
    ../lib/public/linux64/libtier0_client.so \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/libvstdlib_client.so \
    ../lib/public/linux64/mathlib_client.a \
    ../lib/public/linux64/bitmap_client.a \
    ../lib/public/linux64/tier2_client.a \
    ../lib/public/linux64/tier3_client.a \
    ../lib/public/linux64/vtf_client.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxplatform.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx_as2.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxexpat.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxrender_gl.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libjpeg.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libpng.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libz.a \
    ../lib/public/linux64/libsteam_api.so \
    ../lib/public/linux64/libtogl_client.so

unexport LIBFILENAMES

ALL_CUSTOM_BUILD_TOOLS =

unexport ALL_CUSTOM_BUILD_TOOLS

ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES =

unexport ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES

ALL_CUSTOM_BUILD_TOOL_SCRIPTS =

unexport ALL_CUSTOM_BUILD_TOOL_SCRIPTS

ALL_CUSTOM_BUILD_TOOL_OUTPUTS =

unexport ALL_CUSTOM_BUILD_TOOL_OUTPUTS

ALL_DEPGEN_FILES = \
    $(OBJ_DIR)/memoverride.P \
    $(OBJ_DIR)/stdafx.P \
    $(OBJ_DIR)/movieslot.P \
    $(OBJ_DIR)/scaleformuicursorimpl.P \
    $(OBJ_DIR)/scaleformuihighlevelimpl.P \
    $(OBJ_DIR)/scaleformuiinitimpl.P \
    $(OBJ_DIR)/scaleformuimovieimpl.P \
    $(OBJ_DIR)/scaleformuimovieslotimpl.P \
    $(OBJ_DIR)/scaleformuiparamsimpl.P \
    $(OBJ_DIR)/scaleformuirendererimpl.P \
    $(OBJ_DIR)/scaleformuitranslationimpl.P \
    $(OBJ_DIR)/scaleformuivalueimpl.P \
    $(OBJ_DIR)/scaleformuiintegration.P \
    $(OBJ_DIR)/scaleformuitextobjimpl.P \
    $(OBJ_DIR)/scaleformuiimage.P \
    $(OBJ_DIR)/sfuiavatarimage.P \
    $(OBJ_DIR)/sfuichromehtmlimage.P \
    $(OBJ_DIR)/sfuiinventoryimage.P

unexport ALL_DEPGEN_FILES


#
# Include the base makefile now.
#
include $(MAKEFILE_BASE)


#
# Create sentinel directories
#
$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs: scaleformui_linux64.mak | $(OBJ_DIR)/_create_dir
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) create custom build tools dir start
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(TOUCH) $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs


#
# include all the depgen .P files which will include dependency information.
#
include $(wildcard $(OBJ_DIR)/memoverride.P)
include $(wildcard $(OBJ_DIR)/stdafx.P)
include $(wildcard $(OBJ_DIR)/movieslot.P)
include $(wildcard $(OBJ_DIR)/scaleformuicursorimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuihighlevelimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiinitimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuimovieimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuimovieslotimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiparamsimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuirendererimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuitranslationimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuivalueimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiintegration.P)
include $(wildcard $(OBJ_DIR)/scaleformuitextobjimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiimage.P)
include $(wildcard $(OBJ_DIR)/sfuiavatarimage.P)
include $(wildcard $(OBJ_DIR)/sfuichromehtmlimage.P)
include $(wildcard $(OBJ_DIR)/sfuiinventoryimage.P)


#
# Compare/cache a string of compile settings to see if we need to recompile .o's
#
$(eval $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS,COMPILE_O_GLOBAL_SETTINGS,$$(call COMPILE_O_SETTINGS,$$(CFG_CPPFLAGS))))


#
# Compile rules
#
$(OBJ_DIR)/memoverride.o: ../public/tier0/memoverride.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/memoverride.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/memoverride.o

$(OBJ_DIR)/stdafx.o: stdafx.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/stdafx.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/stdafx.o

$(OBJ_DIR)/movieslot.o: scaleformuiimpl/movieslot.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/movieslot.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/movieslot.o

$(OBJ_DIR)/scaleformuicursorimpl.o: scaleformuiimpl/scaleformuicursorimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuicursorimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuicursorimpl.o

$(OBJ_DIR)/scaleformuihighlevelimpl.o: scaleformuiimpl/scaleformuihighlevelimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuihighlevelimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuihighlevelimpl.o

$(OBJ_DIR)/scaleformuiinitimpl.o: scaleformuiimpl/scaleformuiinitimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiinitimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiinitimpl.o

$(OBJ_DIR)/scaleformuimovieimpl.o: scaleformuiimpl/scaleformuimovieimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuimovieimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuimovieimpl.o

$(OBJ_DIR)/scaleformuimovieslotimpl.o: scaleformuiimpl/scaleformuimovieslotimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuimovieslotimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuimovieslotimpl.o

$(OBJ_DIR)/scaleformuiparamsimpl.o: scaleformuiimpl/scaleformuiparamsimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiparamsimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiparamsimpl.o

$(OBJ_DIR)/scaleformuirendererimpl.o: scaleformuiimpl/scaleformuirendererimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuirendererimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuirendererimpl.o

$(OBJ_DIR)/scaleformuitranslationimpl.o: scaleformuiimpl/scaleformuitranslationimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuitranslationimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuitranslationimpl.o

$(OBJ_DIR)/scaleformuivalueimpl.o: scaleformuiimpl/scaleformuivalueimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuivalueimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuivalueimpl.o

$(OBJ_DIR)/scaleformuiintegration.o: scaleformuiimpl/scaleformuiintegration.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiintegration.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiintegration.o

$(OBJ_DIR)/scaleformuitextobjimpl.o: scaleformuiimpl/scaleformuitextobjimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuitextobjimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuitextobjimpl.o

$(OBJ_DIR)/scaleformuiimage.o: scaleformuiimpl/scaleformuiimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiimage.o

$(OBJ_DIR)/sfuiavatarimage.o: scaleformuiimpl/sfuiavatarimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sfuiavatarimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sfuiavatarimage.o

$(OBJ_DIR)/sfuichromehtmlimage.o: scaleformuiimpl/sfuichromehtmlimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sfuichromehtmlimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sfuichromehtmlimage.o

$(OBJ_DIR)/sfuiinventoryimage.o: scaleformuiimpl/sfuiinventoryimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sfuiinventoryimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sfuiinventoryimage.o

endif # (CFG=debug)




















################################################################################
#
# CFG=release
#
################################################################################

ifeq "$(CFG)" "release"

GCC_ExtraCompilerFlags=
GCC_ExtraCxxCompilerFlags=
GCC_ExtraLinkerFlags=
DisableLinkerDeadCodeElimination=
SymbolVisibility=hidden
TreatWarningsAsErrors=false
OptimizerLevel=-gdwarf-4 -g2 $(OptimizerLevel_CompilerSpecific)
PrecompiledHeaderInclude=
SystemLibraries=-lGL 
DLL_EXT=_client.so
SYM_EXT=.dbg
DEVTOOLS := ../devtools
MAKEFILE_BASE := $(DEVTOOLS)/makefile_base_posix.mak
COMPILE_DEPENDANT_MAKEFILES := scaleformui_linux64.mak $(MAKEFILE_BASE)
FORCEINCLUDES= 
DEFINES += -DVPC -DCSTRIKE_REL_BUILD=1 -DRAD_TELEMETRY_DISABLED -DNDEBUG -DGNUC -DPOSIX -DCOMPILER_GCC -DMEMOVERRIDE_MODULE=scaleformui -D_DLL_EXT=_client.so -D_LINUX -DLINUX -DPOSIX -D_POSIX -DDLLNAME=scaleformui -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DUSE_SDL -DCSTRIKE15 -DINCLUDE_SCALEFORM -DENABLE_AMP_SERVER=$ENABLE_AMP_SERVER -DVERSION_SAFE_STEAM_API_INTERFACES -DGL_GLEXT_PROTOTYPES -DDX_TO_GL_ABSTRACTION -DSF_BUILD_SHIPPING -D_DLL_EXT=_client.so -D_DLL_PREFIX=lib -D_EXTERNAL_DLL_EXT=.so -D_LINUX=1 -D_LINUXSTEAMRT64=1 -D_POSIX=1 -DLINUX=1 -DLINUX64=1 -DLINUXSTEAMRT64=1 -DPOSIX=1 -DPROJECTDIR=/home/universe/Downloads/cstrike15_src/scaleformui -DVPCGAME=csgo -DVPCGAMECAPS=CSGO 
INCLUDEDIRS += ../common ../public ../public/tier0 ../public/tier1 ../thirdparty/SDL2 ../scaleformui ../thirdparty/scaleform/sdk42/Include ../thirdparty/scaleform/sdk42/Src ../thirdparty ../common/gl 
CONFTYPE=dll
IMPORTLIBRARY=
OUTPUTFILE=$(OBJ_DIR)/scaleformui_client.so
GAMEOUTPUTFILE=../../game/bin/linux64/scaleformui_client.so

CPPFILES= \
    ../public/tier0/memoverride.cpp \
    stdafx.cpp \
    scaleformuiimpl/movieslot.cpp \
    scaleformuiimpl/scaleformuicursorimpl.cpp \
    scaleformuiimpl/scaleformuihighlevelimpl.cpp \
    scaleformuiimpl/scaleformuiinitimpl.cpp \
    scaleformuiimpl/scaleformuimovieimpl.cpp \
    scaleformuiimpl/scaleformuimovieslotimpl.cpp \
    scaleformuiimpl/scaleformuiparamsimpl.cpp \
    scaleformuiimpl/scaleformuirendererimpl.cpp \
    scaleformuiimpl/scaleformuitranslationimpl.cpp \
    scaleformuiimpl/scaleformuivalueimpl.cpp \
    scaleformuiimpl/scaleformuiintegration.cpp \
    scaleformuiimpl/scaleformuitextobjimpl.cpp \
    scaleformuiimpl/scaleformuiimage.cpp \
    scaleformuiimpl/sfuiavatarimage.cpp \
    scaleformuiimpl/sfuichromehtmlimage.cpp \
    scaleformuiimpl/sfuiinventoryimage.cpp

unexport CPPFILES

LIBFILES = \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/mathlib_client.a \
    ../lib/public/linux64/bitmap_client.a \
    ../lib/public/linux64/tier2_client.a \
    ../lib/public/linux64/tier3_client.a \
    ../lib/public/linux64/vtf_client.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxplatform.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx_as2.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxexpat.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxrender_gl.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libjpeg.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libpng.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libz.a \
    -L../lib/public/linux64 -ltier0_client \
    -L../lib/public/linux64 -lvstdlib_client \
    -L../lib/public/linux64 -lsteam_api \
    -L../lib/public/linux64 -ltogl_client

unexport LIBFILES

LIBFILENAMES = \
    ../lib/public/linux64/libtier0_client.so \
    ../lib/public/linux64/tier1_client.a \
    ../lib/public/linux64/interfaces_client.a \
    ../lib/public/linux64/libvstdlib_client.so \
    ../lib/public/linux64/mathlib_client.a \
    ../lib/public/linux64/bitmap_client.a \
    ../lib/public/linux64/tier2_client.a \
    ../lib/public/linux64/tier3_client.a \
    ../lib/public/linux64/vtf_client.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxplatform.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfx_as2.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxexpat.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/shipping/libgfxrender_gl.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libjpeg.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libpng.a \
    ../thirdparty/scaleform/sdk42/Lib/x86_64-linux/libz.a \
    ../lib/public/linux64/libsteam_api.so \
    ../lib/public/linux64/libtogl_client.so

unexport LIBFILENAMES

ALL_CUSTOM_BUILD_TOOLS =

unexport ALL_CUSTOM_BUILD_TOOLS

ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES =

unexport ALL_CUSTOM_BUILD_TOOL_DEPENDENCIES

ALL_CUSTOM_BUILD_TOOL_SCRIPTS =

unexport ALL_CUSTOM_BUILD_TOOL_SCRIPTS

ALL_CUSTOM_BUILD_TOOL_OUTPUTS =

unexport ALL_CUSTOM_BUILD_TOOL_OUTPUTS

ALL_DEPGEN_FILES = \
    $(OBJ_DIR)/memoverride.P \
    $(OBJ_DIR)/stdafx.P \
    $(OBJ_DIR)/movieslot.P \
    $(OBJ_DIR)/scaleformuicursorimpl.P \
    $(OBJ_DIR)/scaleformuihighlevelimpl.P \
    $(OBJ_DIR)/scaleformuiinitimpl.P \
    $(OBJ_DIR)/scaleformuimovieimpl.P \
    $(OBJ_DIR)/scaleformuimovieslotimpl.P \
    $(OBJ_DIR)/scaleformuiparamsimpl.P \
    $(OBJ_DIR)/scaleformuirendererimpl.P \
    $(OBJ_DIR)/scaleformuitranslationimpl.P \
    $(OBJ_DIR)/scaleformuivalueimpl.P \
    $(OBJ_DIR)/scaleformuiintegration.P \
    $(OBJ_DIR)/scaleformuitextobjimpl.P \
    $(OBJ_DIR)/scaleformuiimage.P \
    $(OBJ_DIR)/sfuiavatarimage.P \
    $(OBJ_DIR)/sfuichromehtmlimage.P \
    $(OBJ_DIR)/sfuiinventoryimage.P

unexport ALL_DEPGEN_FILES


#
# Include the base makefile now.
#
include $(MAKEFILE_BASE)


#
# Create sentinel directories
#
$(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs: scaleformui_linux64.mak | $(OBJ_DIR)/_create_dir
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) create custom build tools dir start
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/locks $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/ranthisbuild $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(MKDIR) -p $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/sentinels $(QUIET_ECHO_POSTFIX)
	$(QUIET_PREFIX) $(TOUCH) $(OBJ_DIR)/_vpc_generated_scripts/custom_build_tools/_vpc_create_dirs


#
# include all the depgen .P files which will include dependency information.
#
include $(wildcard $(OBJ_DIR)/memoverride.P)
include $(wildcard $(OBJ_DIR)/stdafx.P)
include $(wildcard $(OBJ_DIR)/movieslot.P)
include $(wildcard $(OBJ_DIR)/scaleformuicursorimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuihighlevelimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiinitimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuimovieimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuimovieslotimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiparamsimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuirendererimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuitranslationimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuivalueimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiintegration.P)
include $(wildcard $(OBJ_DIR)/scaleformuitextobjimpl.P)
include $(wildcard $(OBJ_DIR)/scaleformuiimage.P)
include $(wildcard $(OBJ_DIR)/sfuiavatarimage.P)
include $(wildcard $(OBJ_DIR)/sfuichromehtmlimage.P)
include $(wildcard $(OBJ_DIR)/sfuiinventoryimage.P)


#
# Compare/cache a string of compile settings to see if we need to recompile .o's
#
$(eval $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS,COMPILE_O_GLOBAL_SETTINGS,$$(call COMPILE_O_SETTINGS,$$(CFG_CPPFLAGS))))


#
# Compile rules
#
$(OBJ_DIR)/memoverride.o: ../public/tier0/memoverride.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/memoverride.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/memoverride.o

$(OBJ_DIR)/stdafx.o: stdafx.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/stdafx.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/stdafx.o

$(OBJ_DIR)/movieslot.o: scaleformuiimpl/movieslot.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/movieslot.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/movieslot.o

$(OBJ_DIR)/scaleformuicursorimpl.o: scaleformuiimpl/scaleformuicursorimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuicursorimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuicursorimpl.o

$(OBJ_DIR)/scaleformuihighlevelimpl.o: scaleformuiimpl/scaleformuihighlevelimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuihighlevelimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuihighlevelimpl.o

$(OBJ_DIR)/scaleformuiinitimpl.o: scaleformuiimpl/scaleformuiinitimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiinitimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiinitimpl.o

$(OBJ_DIR)/scaleformuimovieimpl.o: scaleformuiimpl/scaleformuimovieimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuimovieimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuimovieimpl.o

$(OBJ_DIR)/scaleformuimovieslotimpl.o: scaleformuiimpl/scaleformuimovieslotimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuimovieslotimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuimovieslotimpl.o

$(OBJ_DIR)/scaleformuiparamsimpl.o: scaleformuiimpl/scaleformuiparamsimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiparamsimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiparamsimpl.o

$(OBJ_DIR)/scaleformuirendererimpl.o: scaleformuiimpl/scaleformuirendererimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuirendererimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuirendererimpl.o

$(OBJ_DIR)/scaleformuitranslationimpl.o: scaleformuiimpl/scaleformuitranslationimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuitranslationimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuitranslationimpl.o

$(OBJ_DIR)/scaleformuivalueimpl.o: scaleformuiimpl/scaleformuivalueimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuivalueimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuivalueimpl.o

$(OBJ_DIR)/scaleformuiintegration.o: scaleformuiimpl/scaleformuiintegration.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiintegration.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiintegration.o

$(OBJ_DIR)/scaleformuitextobjimpl.o: scaleformuiimpl/scaleformuitextobjimpl.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuitextobjimpl.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuitextobjimpl.o

$(OBJ_DIR)/scaleformuiimage.o: scaleformuiimpl/scaleformuiimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/scaleformuiimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/scaleformuiimage.o

$(OBJ_DIR)/sfuiavatarimage.o: scaleformuiimpl/sfuiavatarimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sfuiavatarimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sfuiavatarimage.o

$(OBJ_DIR)/sfuichromehtmlimage.o: scaleformuiimpl/sfuichromehtmlimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sfuichromehtmlimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sfuichromehtmlimage.o

$(OBJ_DIR)/sfuiinventoryimage.o: scaleformuiimpl/sfuiinventoryimage.cpp $(call DETECT_STRING_CHANGE_BETWEEN_BUILDS_TIMESTAMP_FILE,COMPILE_O_GLOBAL_SETTINGS) | _precompile_steps
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile start for file $(OBJ_DIR)/sfuiinventoryimage.o
	$(QUIET_PREFIX) $(call SPEW_UPDATED_DEPENDENCIES)
	$(QUIET_PREFIX) $(call RUN_PREBUILD_EVENT_ONCE)
	$(PRE_COMPILE_FILE)
	$(QUIET_PREFIX) $(MKDIR) -p "$(dir $@)"
	$(call COMPILE_FILE, $(CFG_CPPFLAGS)) $(POST_COMPILE_FILE)
	$(QUIET_PREFIX) $(BUILD_DEBUG_ECHO) COMPILE_FILE compile end for file $(OBJ_DIR)/sfuiinventoryimage.o

endif # (CFG=release)
